-- CreateTable
CREATE TABLE "convenio" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "codigo" TEXT,
    "data" TIMESTAMP(3),
    "razao_soc" TEXT NOT NULL,
    "fantasia" TEXT,
    "desconto" DECIMAL(10,2),
    "cgc" TEXT,
    "ie" TEXT,
    "cpf" TEXT,
    "rg" TEXT,
    "endereco" TEXT,
    "bairro" TEXT,
    "cep" TEXT,
    "cidade" TEXT,
    "uf" TEXT,
    "fone" TEXT,
    "fax" TEXT,
    "contato" TEXT,
    "agencia" TEXT,
    "conta" TEXT,
    "banco" TEXT,
    "usuario" TEXT,
    "senha" TEXT,
    "parcelas" INTEGER,
    "mensagem" TEXT,
    "libera" TEXT,
    "email" TEXT,
    "chave" TEXT,
    "convenio" TEXT,
    "nome" TEXT,
    "cnpj" TEXT,
    "tipo" TEXT,
    "estado" TEXT,
    "telefone" TEXT,
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "convenio_pkey" PRIMARY KEY ("id")
);
